Result service idea by k4t & north
StormITpl/EduQuiz pull request #42
Opened 2023-04-14 19:42 UTC by k4t4u

short code for Result Service

2023-04-14 20:00 UTC, k4t4u commented on src/main/java/pl/stormit/eduquiz/result/service/ResultService.java
> +            throw new EntityNotFoundException("The game does not exist with ID: " + gameIdDto);
ale gameIdDto ma tylko ID

2023-04-14 20:19 UTC, MichalMarciniakGS commented on src/main/java/pl/stormit/eduquiz/result/service/ResultService.java
> +            throw new EntityNotFoundException("The game does not exist with ID: " + gameIdDto);
No to jest mała różnica, ale nadal w jedyn wypadku zwracamy obiekt a w drugim samo id
![image](https://user-images.githubusercontent.com/72413371/232147113-49c3bfe7-7d32-4369-8db7-01d78af050b2.png)

2023-04-17 18:55 UTC, JacekRG approved these changes

2023-04-17 19:24 UTC, Manes79 approved these changes

2023-04-17 20:14 UTC, RobertoJavaDev requested changes

2023-04-17 20:14 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/eduquiz/result/service/ResultService.java
> +            throw new EntityNotFoundException("The game does not exist with ID: " + gameIdDto);
Add changes in line with KisielKing comments and I'll give approval
Everything else looks like good.

2023-04-24 06:37 UTC, RobertoJavaDev approved these changes

2023-04-25 17:25 UTC, merged