refactoring test sector
StormITpl/EduQuiz pull request #48
Opened 2023-04-29 11:20 UTC by k4t4u

2023-04-30 07:38 UTC, RobertoJavaDev requested changes

2023-04-30 07:38 UTC, RobertoJavaDev commented on src/test/java/pl/stormit/eduquiz/game/PlayGameIntegrationTest.java
>          //when
Please correct each section: given/when/then ->
from:
//given
//when
//then

into:
// given
// when
// then
*Tomek pointed this out in code review

2023-04-30 07:38 UTC, RobertoJavaDev commented on src/test/java/pl/stormit/eduquiz/quizcreator/controllers/AnswerApiControllerTest.java
Delete redundant ";" in line 55.

2023-04-30 07:38 UTC, RobertoJavaDev commented on src/test/java/pl/stormit/eduquiz/quizcreator/controllers/QuizApiControllerTest.java
> +        result.andExpect(status().isOk()).andExpect(content().string(containsString("PL"))).andExpect(content().string(containsString("UK")));
I think the previous assert version is more readable:
result.andExpect(status().isOk())
                .andExpect(content().string(containsString("PL")))
                .andExpect(content().string(containsString("UK")));
               
You can see immediately what we are checking

2023-04-30 07:38 UTC, RobertoJavaDev commented on src/test/java/pl/stormit/eduquiz/quizcreator/controllers/QuizApiControllerTest.java
> +        MockHttpServletRequestBuilder content = post("/api/v1/quizzes").contentType(MediaType.APPLICATION_JSON).content(dtoAsString);
The same like above

2023-04-30 07:38 UTC, RobertoJavaDev commented on src/test/java/pl/stormit/eduquiz/quizcreator/controllers/QuizApiControllerTest.java
> +        mockMvc.perform(content).andExpect(status().isOk()).andDo(MockMvcResultHandlers.print());
The same like above

2023-04-30 07:38 UTC, RobertoJavaDev commented on src/test/java/pl/stormit/eduquiz/quizcreator/controllers/UserApiControllerTest.java
> -                .andDo(MockMvcResultHandlers.print());
The same like above

2023-04-30 07:38 UTC, RobertoJavaDev commented on src/test/java/pl/stormit/eduquiz/quizcreator/controllers/UserApiControllerTest.java
> +        mockMvc.perform(get(userUrl)).andExpect(status().isOk()).andExpect(content().string(containsString("Ananiasz"))).andDo(MockMvcResultHandlers.print());
The same like above

2023-05-01 06:18 UTC, RobertoJavaDev approved these changes

2023-05-01 08:53 UTC, Manes79 approved these changes

2023-05-01 20:26 UTC, JacekRG approved these changes

2023-05-04 06:34 UTC, merged