Task52_ImplementingHTMLtoPassTheEntireQuiz
StormITpl/EduQuiz pull request #52
Opened 2023-05-18 20:18 UTC by MichalMarciniakGS

Work in progress

2023-05-19 22:45 UTC, JacekRG approved these changes

2023-06-17 16:21 UTC, k4t4u approved these changes
Good Job!

2023-06-17 19:12 UTC, RobertoJavaDev requested changes

2023-06-17 19:12 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/eduquiz/game/service/GameService.java
> +        System.out.println("USER ANSWERS: " + userAnswers); //Test
I think this Sout is unnecessary.

2023-06-18 08:05 UTC, JacekRG approved these changes

2023-06-18 09:44 UTC, merged