Task58
StormITpl/EduQuiz pull request #67
Opened 2023-09-20 15:46 UTC by k4t4u

2023-09-20 16:11 UTC, Slawek84PL commented on src/main/java/pl/stormit/eduquiz/quizcreator/domain/user/Role.java
> +    ADMIN,
```suggestion
    ROLE_USER,
    ROLE_ADMIN,
```

2023-09-20 16:28 UTC, k4t4u commented on src/main/java/pl/stormit/eduquiz/quizcreator/domain/user/Role.java
> +    ADMIN,
Zmienione

2023-09-20 18:05 UTC, RobertoJavaDev requested changes
Maybe we should add status: verified, unverified, blocked - instead of active, inactive.
We have this information in Notion from the last meeting

2023-09-20 18:12 UTC, RobertoJavaDev requested changes
What about the DTO layer?

2023-09-20 18:12 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/eduquiz/quizcreator/domain/user/Status.java
> +    INACTIVE,
Maybe we should add status: verified, unverified, blocked - instead of active, inactive.
We have this information in Notion from the last meeting.

2023-09-20 18:12 UTC, RobertoJavaDev commented on src/main/java/pl/stormit/eduquiz/quizcreator/domain/user/User.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
@GeneratedValue annotation is enough in this situation

2023-09-20 19:42 UTC, k4t4u commented
> What about the DTO layer?

The current DTO is used in 45 places and is created as a record. I don't want to touch it because starting tomorrow evening, I'll be away for 9 days, and I won't have time to finish it.

2023-09-21 07:52 UTC, RobertoJavaDev approved these changes

2023-09-21 09:32 UTC, merged