Added Swagger, only dependency
StormITpl/EduQuiz pull request #69
Opened 2023-09-21 10:42 UTC by Magdalenacze

http://localhost:8080/swagger-ui/index.html

2023-09-21 14:36 UTC, k4t4u approved these changes

2023-09-23 05:18 UTC, RobertoJavaDev requested changes
If you can, please add new section to readme.md file:
**API Documentation**
With description: "The API documentation can be accessed after starting the project at http://localhost:8080/swagger-ui/index.html"

2023-09-23 05:18 UTC, RobertoJavaDev commented on pom.xml
> +            <version>2.0.2</version>
Please, bump up the version to newest - 2.1.0

2023-09-26 18:08 UTC, RobertoJavaDev approved these changes

2023-09-27 09:23 UTC, merged